NASA_ARMS:
        x_min: -1.0
        x_max: 0.9
        y_min: -1.0
        y_max: 1.0
        z_min: 1.0
        z_max: 4.5

        obstacle_preprocessor:
                accumulate_count: 4

        obstacle_processor:
                block_size: 0.0375
                dev_percent: 0.9

                downsame_input_data: true
                downsample_size: 0.015

                passthrough_filter_enable: true

                statistical_outlier_meanK: 15
                statistical_outlier_stdDevThres: 1.0

                plane_segment_dist_thres: 0.040
                plane_segment_angle: 20

                euc_cluster_tolerance: 0.4
                euc_min_cluster_size: 5
                euc_max_cluster_size: 20000
                convex_hull_alpha: 180.0
